[
  {
    rand: "ORIENT",
    id: "1",
    product: [
      {
        id_product: "1",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "5",
        origin: "Nhật Bản",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://donghohaitrieu.com/wp-content/uploads/2023/09/RA-AC0F12S10B.jpg",
        name: "ORIENT RA-AC0F12S10B",
        price: "35000000",
        salecost: "20",
        popular: "popular",
        bestseller: "bestseller",
        new: "new",
        genre: "Nam",
        title:
          "Orient RA-AC0F12S10B – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "RA-AC0F12S10B",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam Orient RA-AC0F12S10B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "Orient RA-AC0F12S10B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "2",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "4",
        origin: "Nhật Bản",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/RA-NR2001G10B.jpg",
        name: "ORIENT RA-AC0F08G10B",
        price: "19000000",
        salecost: "30",
        bestseller: "",
        popular: "popular",
        new: "new",
        genre: "Nữ",
        title:
          "ORIENT RA-AC0F08G10B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606924",
        dial_color: "Vàng",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ ORIENT RA-AC0F08G10B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT RA-AC0F08G10B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "3",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "3",
        origin: "Nhật Bản",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/RF-QA0009S10B.jpg",
        name: "ORIENT RF-QA0009S10B",
        price: "20000000",
        salecost: "20",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "Orient RF-QA0009S10B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "RF-QA0009S10B",
        dial_color: "Vàng",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ Orient RF-QA0009S10B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "Orient RF-QA0009S10B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "4",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "2",
        origin: "Nhật Bản",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/RE-AU0306L00B.jpg",
        name: "ORIENT STAR RE-AU0306L00B",
        price: "10000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "ORIENT STAR RE-AU0306L00B – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L2.128.4.57.6",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nam ORIENT STAR RE-AU0306L00B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT STAR RE-AU0306L00B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "5",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "1",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/RE-AU0306L00B.jpg",
        name: "ORIENT RA-AC0E07S10B",
        price: "6060000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "ORIENT RA-AC0E07S10B – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Kim Loại",
        seri: "RA-AC0E07S10B",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nam ORIENT RA-AC0E07S10B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT RA-AC0E07S10B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "6",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "5",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/46_RF-QD0002B10B.jpg",
        name: "ORIENT RF-QD0002B10B",
        price: "4020000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "ORIENT RF-QD0002B10B – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Da",
        seri: "RF-QD0002B10B",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nam ORIENT RF-QD0002B10B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT RF-QD0002B10B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "7",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "5",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/RE-AT0108L00B.jpg",
        name: "ORIENT RE-AT0108L00B",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "ORIENT RE-AT0108L00B – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Da",
        seri: "RE-AT0108L00B",
        dial_color: "Xanh",
        Waterproof: "Lặn Biển (20 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nam ORIENT RE-AT0108L00B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT RE-AT0108L00B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "8",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "4",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/315_RA-KA0005A00B.jpg",
        name: "ORIENT MOON RA-KA0005A00B",
        price: "8000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "ORIENT MOON RA-KA0005A00B – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Da",
        seri: "RA-KA0005A00B",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ ORIENT MOON RA-KA0005A00B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT MOON RA-KA0005A00B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "9",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "3",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/315_RA-KA0005A00B.jpg",
        name: "ORIENT FGW0100AW0",
        price: "8000000",
        salecost: "",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "ORIENT FGW0100AW0 – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Da",
        seri: "FGW0100AW0",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ ORIENT FGW0100AW0 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT FGW0100AW0 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "10",
        rand_product: "ORIENT",
        quantity: 1,
        rank: "2",
        origin: "Nhật Bản",
        terrible: "Mineral Crystal (Kính cứng)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FKU00003W0.jpg",
        name: "ORIENT FKU00003W0",
        price: "8020000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "ORIENT FKU00003W0 – Nam – Kính Mineral Crystal – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FKU00003W0",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ ORIENT FKU00003W0 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "ORIENT ORIENT FKU00003W0 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
  {
    rand: "MOVADO",
    id: "2",
    product: [
      {
        id_product: "11",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "1",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/3600201.jpg",
        name: "MOVADO MUSEUM SOFIE",
        price: "",
        salecost: "50",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "MOVADO 0606930 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606930",
        dial_color: "Vàng",
        Waterproof: "Đi Tắm (5ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO 0606930 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO MUSEUM SOFIE mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
        content_Product1:
          "MOVADO MUSEUM SOFIE Sử dụng động cơ tự động hoặc pin, đồng hồ MOVADO MUSEUM SOFIE đảm bảo độ chính xác cao và độ bền lâu dài. của mỗi chiếc đồng hồ OMEGA đều được kiểm soát chặt chẽ, thể hiện sự chuyên nghiệp và tâm huyết của thương hiệu. MOVADO MUSEUM SOFIE thường được thiết kế để phù hợp với nhiều dịp khác nhau, từ bữa tiệc trang trí đến ngày công sở, tạo điểm nhấn tốt cho phong cách cá nhân của người đeo. Lưu ý rằng các thông số kỹ thuật cụ thể và mẫu mã có thể thay đổi theo từng phiên bản cụ thể của MOVADO MUSEUM SOFI.",
      },
      {
        id_product: "12",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2017/09/23_606114-2.jpg",
        name: "MOVADO MUSEUM 70TH",
        price: "30000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "Movado 0606920 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606920",
        dial_color: "Bạc",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam Movado 0606920 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO MUSEUM 70TH mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "13",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2021/02/movado-0607114.jpg",
        name: "MOVADO MUSEUM EDITION",
        price: "10000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "MOVADO 0606925 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606925",
        dial_color: "Vàng",
        Waterproof: "Đi Bơi (10ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO 0606925 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO MUSEUM EDITION mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "14",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "1",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/3680016.jpg",
        name: "MOVADO 3680016",
        price: "10000000",
        salecost: "30",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "MOVADO 3680016 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "3680016",
        dial_color: "Vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO 3680016 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO 3680016 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "15",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/3680012.jpg",
        name: "MOVADO 3680012",
        price: "10000000",
        salecost: "30",
        bestseller: "bestseller",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "MOVADO 3680012 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "3680012",
        dial_color: "Bạc",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO 3680012 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO 3680012 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "16",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2017/01/0606916-2.jpg",
        name: "MOVADO 0606916",
        price: "10200000",
        salecost: "10",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "MOVADO 0606916 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "3680012",
        dial_color: "Vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO 0606916 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO 0606916 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "17",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://donghotantan.vn/images/products/2023/10/26/large/dong-ho-movado-3650158-4_1698294925.jpg",
        name: "MOVADO HERITAGE",
        price: "10200000",
        salecost: "10",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "MOVADO HERITAGE – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "3650158",
        dial_color: "Vàng",
        Waterproof: "Lặn Biển (20 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ MOVADO HERITAGE có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO HERITAGE mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
        content_Product1:
          "Sử dụng động cơ tự động hoặc pin, đồng hồ MOVADO HERITAGE đảm bảo độ chính xác cao và độ bền lâu dài. của mỗi chiếc đồng hồ MOVADO đều được kiểm soát chặt chẽ, thể hiện sự chuyên nghiệp và tâm huyết của thương hiệu. MOVADO HERITAGE thường được thiết kế để phù hợp với nhiều dịp khác nhau, từ bữa tiệc trang trí đến ngày công sở, tạo điểm nhấn tốt cho phong cách cá nhân của người đeo. Lưu ý rằng các thông số kỹ thuật cụ thể và mẫu mã có thể thay đổi theo từng phiên bản cụ thể của MOVADO HERITAG.",
      },
      {
        id_product: "18",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://donghotantan.vn/images/products/2023/10/26/large/dong-ho-movado-3601083-1_1698290500.jpg",
        name: "MOVADO BOLD",
        price: "10200000",
        salecost: "10",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "MOVADO BOLD – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "3601083",
        dial_color: "Đen",
        Waterproof: "Lặn Biển (20 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ MOVADO BOLD có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO BOLD mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "19",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://donghotantan.vn/images/products/2021/02/11/large/dong-ho-movado-3600626-.jpg",
        name: "MOVADO QUARTZ",
        price: "15000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "MOVADO QUARTZ – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Cao Su",
        seri: "3600626",
        dial_color: "Đen",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Cao Su",
        content:
          "Đồng hồ Nữ MOVADO QUARTZ có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO QUARTZ mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "20",
        rand_product: "MOVADO",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://donghotantan.vn/images/products/2022/03/24/large/dong-ho-movado-0607553_1648091496.jpg",
        name: "MOVADO AUTOMATIC",
        price: "10000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "MOVADO AUTOMATIC – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0607553",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MOVADO AUTOMATIC có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MOVADO AUTOMATIC mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
  {
    rand: "FREDERIQUE",
    id: "3",
    product: [
      {
        id_product: "21",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/11/FC-206MPND1S6.jpg",
        name: "FREDERIQUE FC-312V4S4",
        price: "55000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "FREDERIQUE 0606918 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606918",
        dial_color: "Đen",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam FREDERIQUE 0606918 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-312V4S4 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "22",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FC-240GRS5B6.jpg",
        name: "FREDERIQUE CONSTANT",
        price: "55000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "FREDERIQUE CONSTANT FC-240GRS5B6 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FC-240GRS5B6",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam FREDERIQUE CONSTANT có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE CONSTANT mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "23",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2021/02/42_FC-200M1ER3B.jpg",
        name: "FREDERIQUE CLASSICS FC",
        price: "20000000",
        salecost: "5",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "FREDERIQUE CLASSICS FC 200M1ER3B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "200M1ER3B",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ FREDERIQUE CLASSICS FC có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE CLASSICS FC mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "24",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/40_FC-310V4NH4.jpg",
        name: "FREDERIQUE HIGHLIFE",
        price: "20000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "FREDERIQUE HIGHLIFE 310V4NH4 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "310V4NH4",
        dial_color: "vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam FREDERIQUE HIGHLIFE có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE HIGHLIFE mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "25",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/42_FC-702G3S4.jpg",
        name: "FREDERIQUE FC-702G3S4",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "FREDERIQUE FC-702G3S4 310V4NH4 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "FC-702G3S4",
        dial_color: "vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam FREDERIQUE FC-702G3S4 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-702G3S4 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "26",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/176_FC-315M4P6B3.jpg",
        name: "FREDERIQUE FC-315M4P6B3",
        price: "10000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "FREDERIQUE FC-702G3S4 310V4NH4 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FC-315M4P6B3",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam FREDERIQUE FC-315M4P6B3 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-315M4P6B3 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "27",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FC-282AS5B4-1.jpg",
        name: "FREDERIQUE FC-282AS5B4",
        price: "50000000",
        salecost: "",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "FREDERIQUE FC-282AS5B4 310V4NH4 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "FC-282AS5B4",
        dial_color: "Vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam FREDERIQUE FC-282AS5B4 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-282AS5B4 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "28",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FC-206MPWD1S5B.jpg",
        name: "FREDERIQUE FC-206MPWD1S5B",
        price: "50000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "FREDERIQUE FC-206MPWD1S5B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FC-206MPWD1S5B",
        dial_color: "Vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam FREDERIQUE FC-206MPWD1S5B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-206MPWD1S5B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
        content_Product1:
          "Sử dụng động cơ tự động hoặc pin, đồng hồ FREDERIQUE FC-206MPWD1S5B đảm bảo độ chính xác cao và độ bền lâu dài.Chất lượng chế tác của mỗi chiếc đồng hồ FREDERIQUE đều được kiểm soát chặt chẽ, thể hiện sự chuyên nghiệp và tâm huyết của thương hiệu. FREDERIQUE FC-206MPWD1S5B thường được thiết kế để phù hợp với nhiều dịp khác nhau, từ bữa tiệc trang trí đến ngày công sở, tạo điểm nhấn tốt cho phong cách cá nhân của người đeo. Lưu ý rằng các thông số kỹ thuật cụ thể và mẫu mã có thể thay đổi theo từng phiên bản cụ thể của FREDERIQUE FC-206MPWD1S.",
      },
      {
        id_product: "29",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FC-200WHD1ER32B.jpg",
        name: "FREDERIQUE FC-200WHD1ER32B",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "FREDERIQUE FC-200WHD1ER32B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FC-200WHD1ER32B",
        dial_color: "Vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam FREDERIQUE FC-200WHD1ER32B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-200WHD1ER32B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "30",
        rand_product: "FREDERIQUE",
        quantity: 1,
        rank: "1",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/FC-206MPWD1S5B.jpg",
        name: "FREDERIQUE FC-206MPWD1S5B",
        price: "10200000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "FREDERIQUE FC-206MPWD1S5B – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "FC-206MPWD1S5B",
        dial_color: "Vàng",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam FREDERIQUE FC-206MPWD1S5B có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "FREDERIQUE FC-206MPWD1S5B mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
  {
    rand: "MICHAEL KORS",
    id: "4",
    product: [
      {
        id_product: "31",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "5",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK6941.jpg",
        name: "MICHAEL KORS CHRONOGRAPH",
        price: "55550000",
        salecost: "",
        bestseller: "",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "MICHAEL 0606921 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606921",
        dial_color: "vàng",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MICHAEL 0606921 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS CHRONOGRAPH mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "32",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "2",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK2857.jpg",
        name: "MICHAEL KORS CELESTIAL",
        price: "50000000",
        salecost: "",
        bestseller: "bestseller",
        new: "new",
        popular: "",
        genre: "Nữ",
        title:
          "MICHAEL 0606922 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606922",
        dial_color: "Vàng",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ MICHAEL 0606922 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS CELESTIAL mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "33",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "4",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK7229.jpg",
        name: "MICHAEL KORS MINI SOFIE",
        price: "6000000",
        salecost: "10",
        bestseller: "bestseller",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "MICHAEL 0606928 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606928",
        dial_color: "Vàng",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MICHAEL 0606928 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MINI SOFIE mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "34",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "1",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK8572.jpg",
        name: "MICHAEL KORS MK8572",
        price: "60000000",
        salecost: "20",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "new",
        title:
          "MICHAEL KORS MK8572 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Cao Su",
        seri: "MK8572",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Cao Su",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK8572 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK8572 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "35",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "2",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK4284.jpg",
        name: "MICHAEL KORS MK4284",
        price: "60000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "new",
        title:
          "MICHAEL KORS MK4284 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "MK4284",
        dial_color: "Vàng",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK4284 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK4284 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "36",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "3",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/84_MK3839.jpg",
        name: "MICHAEL KORS MK3839",
        price: "30000000",
        salecost: "",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "",
        title:
          "MICHAEL KORS MK3839 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "MK3839",
        dial_color: "Vàng",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK3839 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK3839 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "37",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "5",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/12_MK2779.jpg",
        name: "MICHAEL KORS MK2779",
        price: "4420000",
        salecost: "",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "",
        title:
          "MICHAEL KORS MK2779 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "MK2779",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK2779 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK2779 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "38",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "3",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/8103-MK5866.jpg",
        name: "MICHAEL KORS MK5866",
        price: "7420000",
        salecost: "",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "",
        title:
          "MICHAEL KORS MK5866 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "MK5866",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK5866 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK5866 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "39",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "3",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK4643.jpg",
        name: "MICHAEL KORS MK4643",
        price: "7420000",
        salecost: "",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "new",
        title:
          "MICHAEL KORS MK4643 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "MK4643",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ NữMICHAEL KORS MK4643 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK5866 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "40",
        rand_product: "MICHAEL KORS",
        quantity: 1,
        rank: "2",
        origin: "Mỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/MK7256.jpg",
        name: "MICHAEL KORS MK7256",
        price: "7420000",
        salecost: "",
        bestseller: "",
        popular: "",
        genre: "Nữ",
        new: "new",
        title:
          "MICHAEL KORS MK7256 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "MK7256",
        dial_color: "Vàng",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ MICHAEL KORS MK7256 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "MICHAEL KORS MK5866 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
  {
    rand: "TISSOT",
    id: "5",
    product: [
      {
        id_product: "41",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T137.410.16.041.00.jpg",
        name: "TISSOT T137.410.16.041",
        price: "10330000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "new",
        genre: "Nam",
        title:
          "TISSOT T137.410.16.041 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "T137.410.16.041",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ Nam TISSOT T137.410.16.041 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T137.410.16.041 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "42",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T063.617.16.057.00.jpg",
        name: "TISSOT LE LOCLE T006",
        price: "50000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nam",
        title:
          "TISSOT 0606919 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "0606919",
        dial_color: "Nâu Vàng",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam TISSOT 0606919 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT LE LOCLE T006 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "43",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/10/T137.407.11.351.00.jpg",
        name: "TISST LOVELY SQUARE",
        price: "10330000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "TISSOT 0606931 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606931",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ TISSOT 0606919 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "Tissot Lovely Square T006 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "44",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T122.417.16.033.00.jpg",
        name: "TISSOT LE LOCLE T001",
        price: "15000000",
        salecost: "15",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "TISSOT 0606929 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "0606929",
        dial_color: "Trắng",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam TISSOT 0606929 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "Tissot Le Locle T001 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "45",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T133.210.36.056.00.jpg",
        name: "TISSOT T T133.210.36.056.00",
        price: "15000000",
        salecost: "15",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nữ",
        title:
          "TISSOT T T133.210.36.056.00 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "T133.210.36.056.00",
        dial_color: "Nâu",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nữ TISSOT T T133.210.36.056.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T T133.210.36.056.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "46",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "1",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T122.210.16.373.00.jpg",
        name: "TISSOT T122.210.16.373.00",
        price: "15000000",
        salecost: "5",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "T122.210.16.373.00 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "T122.210.16.373.00",
        dial_color: "Trắng",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nữ TISSOT T122.210.16.373.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T122.210.16.373.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "47",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T122.407.16.043.00.jpg",
        name: "TISSOT T122.407.16.043.00",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "TISSOT T122.407.16.043.00 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "T122.407.16.043.00",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam TISSOT T122.407.16.043.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T122.407.16.043.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "48",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T122.417.11.011.00.jpg",
        name: "TISSOT T122.417.11.011.00",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "TISSOT T122.417.11.011.00 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "T122.417.11.011.00",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam TISSOT T122.417.11.011.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T122.417.11.011.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "49",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T122.407.16.031.00.jpg",
        name: "TISSOT T122.407.16.031.00",
        price: "20000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "TISSOT T122.407.16.031.00 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "T122.407.16.031.00",
        dial_color: "Bạc",
        Waterproof: "Đi Bơi (10 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam TISSOT T122.407.16.031.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T122.407.16.031.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "50",
        rand_product: "TISSOT",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/T097.410.11.058.00.jpg",
        name: "TISSOT T097.410.11.058.00",
        price: "30000000",
        salecost: "",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "TISSOT T097.410.11.058.00 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "T097.410.11.058.00",
        dial_color: "Bạc",
        Waterproof: "Đi Mưa Nhỏ (3ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam TISSOT T097.410.11.058.00 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "TISSOT T097.410.11.058.00 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
  {
    rand: "LONGINES",
    id: "6",
    product: [
      {
        id_product: "51",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "28 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L2.128.4.57.6.jpg",
        name: "LONGINES L2.128.4.57.6",
        price: "10000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "LONGINES MASTER L2.128.4.57.6 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L2.128.4.57.6",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ LONGINES L2.128.4.57.6 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L2.128.4.57.6 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
        content_Product1:
          "Sử dụng động cơ tự động hoặc pin, đồng hồ LONGINES L2.128.4.57.6 đảm bảo độ chính xác cao và độ bền lâu dài.Chất lượng chế tác của mỗi chiếc đồng hồ LONGINES đều được kiểm soát chặt chẽ, thể hiện sự chuyên nghiệp và tâm huyết của thương hiệu. LONGINES L2.128.4.57.6 thường được thiết kế để phù hợp với nhiều dịp khác nhau, từ bữa tiệc trang trí đến ngày công sở, tạo điểm nhấn tốt cho phong cách cá nhân của người đeo. Lưu ý rằng các thông số kỹ thuật cụ thể và mẫu mã có thể thay đổi theo từng phiên bản cụ thể của LONGINES L2.128.4.57.",
      },
      {
        id_product: "52",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "30 mm",
        img: "https://donghohaitrieu.com/wp-content/uploads/2023/09/42_L4.716.4.52.6.jpg",
        name: "LONGINES L4.716.4.52.6",
        price: "10000000",
        salecost: "",
        bestseller: "bestseller",
        popular: "popular",
        new: "",
        genre: "Nữ",
        title:
          "LONGINES L4.716.4.52.6 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L2.128.4.57.6",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ Nữ LONGINES L4.716.4.52.6 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L4.716.4.52.6 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "53",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L2.893.4.97.0.jpg",
        name: "LONGINES L2.893.4.97.0",
        price: "10000000",
        salecost: "20",
        bestseller: "",
        popular: "",
        genre: "Nam",
        new: "new",
        title:
          "LONGINES L2.893.4.97.0 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L2.893.4.97.0",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam LONGINES L2.893.4.97.0 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L2.893.4.97.0 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "54",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L4.984.3.22.7.jpg",
        name: "LONGINES MASTER WATCH",
        price: "30000000",
        salecost: "10",
        bestseller: "",
        popular: "popular",
        new: "new",
        genre: "Nam",
        title:
          "LONGINES 0606923 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "0606923",
        dial_color: "Vàng Gold",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nam LONGINES 0606923 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES MASTER WATCH mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "55",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "40 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/46_L4.921.4.52.2.jpg",
        name: "LONGINES L4.921.4.52.2",
        price: "10000000",
        salecost: "10",
        bestseller: "",
        popular: "popular",
        new: "new",
        genre: "Nam",
        title:
          "LONGINES L4.921.4.52.2 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "L4.921.4.52.2",
        dial_color: "Bạc",
        Waterproof: "Đi Tắm (5 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam LONGINES L4.921.4.52.2 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L4.921.4.52.2 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "56",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "4",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "44 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/208_L1.611.4.52.2.jpg",
        name: "LONGINES L1.611.4.52.2",
        price: "15000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "LONGINES L1.611.4.52.2 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "L1.611.4.52.2",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam LONGINES L1.611.4.52.2 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L1.611.4.52.2 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
        content_Product1:
          "Sử dụng động cơ tự động hoặc pin, đồng hồ LONGINES L1.611.4.52.2 đảm bảo độ chính xác cao và độ bền lâu dài. của mỗi chiếc đồng hồ LONGINES đều được kiểm soát chặt chẽ, thể hiện sự chuyên nghiệp và tâm huyết của thương hiệu. LONGINES L1.611.4.52.2 thường được thiết kế để phù hợp với nhiều dịp khác nhau, từ bữa tiệc trang trí đến ngày công sở, tạo điểm nhấn tốt cho phong cách cá nhân của người đeo. Lưu ý rằng các thông số kỹ thuật cụ thể và mẫu mã có thể thay đổi theo từng phiên bản cụ thể của LONGINES L1.611.4.52.",
      },
      {
        id_product: "57",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L4.821.4.52.6.jpg",
        name: "LONGINES L4.821.4.52.6",
        price: "15000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nam",
        title:
          "LONGINES L4.821.4.52.6 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "L4.821.4.52.6",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam LONGINES L4.821.4.52.6 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L4.821.4.52.6 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "58",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "2",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L4.209.2.11.7-1.jpg",
        name: "LONGINES L4.209.2.11.7",
        price: "15000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "LONGINES  L4.209.2.11.7 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L4.209.2.11.7",
        dial_color: "Bạc",
        Waterproof: "Lặn Biển (20 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nữ LONGINES  L4.209.2.11.7 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES  L4.209.2.11.7 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "59",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "3",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "26 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L4.274.4.12.6.jpg",
        name: "LONGINES L4.274.4.12.6",
        price: "15000000",
        salecost: "10",
        bestseller: "",
        popular: "",
        new: "",
        genre: "Nữ",
        title:
          "LONGINES  L4.274.4.12.6 – Nữ – Kính Sapphire – Automatic (Tự Động) – Dây Kim Loại",
        seri: "L4.274.4.12.6",
        dial_color: "Bạc",
        Waterproof: "Lặn Biển (20 ATM)",
        strap: "Dây Kim Loại",
        content:
          "Đồng hồ nữ LONGINES  L4.274.4.12.6 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES  L4.274.4.12.6 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
      {
        id_product: "60",
        rand_product: "LONGINES",
        quantity: 1,
        rank: "5",
        origin: "Thụy Sỹ",
        terrible: "Sapphire (Kính Chống Trầy)",
        machine: "Automatic (Tự Động)",
        dial_diameter: "38 mm",
        img: "https://image.donghohaitrieu.com/wp-content/uploads/2023/09/L4.795.4.78.2.jpg",
        name: "LONGINES L4.795.4.78.2",
        price: "15000000",
        salecost: "20",
        bestseller: "",
        popular: "",
        new: "new",
        genre: "Nam",
        title:
          "LONGINES LONGINES L4.795.4.78.2 – Nam – Kính Sapphire – Automatic (Tự Động) – Dây Da",
        seri: "L4.795.4.78.2",
        dial_color: "Bạc",
        Waterproof: "Lặn Sâu (30 ATM)",
        strap: "Dây Da",
        content:
          "Đồng hồ nam LONGINES L4.795.4.78.2 có mặt số tròn truyền thống với viền mỏng tinh tế, kim chỉ và logo dấu chấm đặc trưng được phủ vàng nổi bật trên nền số màu đen mạnh mẽ, dây đeo demi đem đến nét thời trang sang trọng.",
        content_Product:
          "LONGINES L4.795.4.78.2 mang đến một thiết kế tinh tế và lịch lãm, thường có vỏ làm từ thép không gỉ cao cấp, tạo cảm giác sang trọng và bền bỉ.",
      },
    ],
  },
];
